### ISSUE TITLE
Output list of build directory

### ISSUE THREAD

**Issue by alignsoft** [skipjack/directory-tree-webpack-plugin#2] opened 2018-08-07 19:08 UTC
My understanding is that I just need to add the following to my webpack.config 

```
const DirectoryTreePlugin = require('directory-tree-webpack-plugin')

        new DirectoryTreePlugin({
            dir: './build',
            path: './build_js.json',
            extensions: /\.js/
        }),
```

In my case, I'm trying to export a build_js.json file that includes a list of all the .js files in the build directory at the root of the project folder.

When I build the project, I'm not seeing any errors, and I'm not getting the build_js.json file output anywhere.

Am I missing something?

Also, I'd like to iterate through an assets directory and generate a list of everything contained within - jpg, css, json files etc., each in their own subdirectories. Can I configure a second plugin definition to do so? Something like this (with both)?

```
        new DirectoryTreePlugin({
            dir: './build',
            path: './build_js.json',
            extensions: /\.js/
        }),
        new DirectoryTreePlugin({
            dir: './assets',
            path: './assets.json',
            extensions: /\.*/
        }),

```
I'm using Webpack 3.11.0

**Comment by skipjack** [comment] 2018-08-08 12:22
Yeah, this use case isn't supported by the plugin. The issue is that your `./build` directory likely doesn't exist (or is in the process of being rebuilt) when the plugin runs. The kind of stats (e.g. bundle file names/paths) you're looking for should be available by using webpack's [node api](https://webpack.js.org/api/node/). The `./assets` definition should work assuming that the directory isn't created through webpack (like `./build` assumably is).

The other issue is that if you're on webpack v4, this plugin might not work (see my comment on #1). I'll be updating it soon to fix that though.

**Comment by skipjack** [comment] 2018-08-08 12:23
If you share an example repository, I'd be willing to take a look and help you out.

**Comment by alignsoft** [comment] 2018-08-08 22:01
The build directory issue makes perfect sense, and if I remove the build configuration from the webpack config, the assets.json exports as expected.

Can I pass an array of extensions?

`  extensions: [/\.js/,/\.json/,/\.jpg/,] 
`

Is there any way to pass a list of extensions to exclude instead?

For example, my assets directory contains jpg/png/json/js/svg/pdf/css etc., all of which I want, but also contains .svn files, which I want to exclude. It would be great to be able to exclude the one file type rather than include all the others.

That said, the plugin is extremely useful as is, so thanks very much for your time!

**Comment by skipjack** [comment] 2018-08-25 23:35
Sorry for the delayed response...

> Can I pass an array of extensions?
> 
> `extensions: [/\.js/,/\.json/,/\.jpg/,]`

No, as noted in the [readme](), this plugin passes all other options (e.g. `extensions`) over to the `directory-tree` package which only [supports a single regex](https://github.com/mihneadb/node-directory-tree#options). So you would use the following instead:

``` js
extensions: /\.(js|json|jpg)/
```

However, see their docs because there's also an `exclude` option which might better fit your needs. I'm going to close this as I don't think there's a particular bug or enhancement mentioned here but feel free to comment with anything else and I'll do my best to answer.

**Closed as completed by skipjack** 2018-08-25 23:35 UTC
